os:
  - osx
language: node_js
node_js:
  - "stable"
cache:
directories:
  - "node_modules"
install:
  - yarn install
script:
  - yarn build
  - if [ $TRAVIS_BRANCH = 'master' ]; then CLIENT_ID=${CLIENT_ID} CLIENT_SECRET=${CLIENT_SECRET} EXTENSION_ID=${EXTENSION_ID} REFRESH_TOKEN=${REFRESH_TOKEN} node ./deploy.js; fi

